# .pre-commit-config.yaml
repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: v4.2.0
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, postgres,]
        types: [sql]
        files: \.(sql)$ # Target SQL files
      - id: sqlfluff-fix
        args: [--dialect, postgres, --exclude-rules, L001, L002, --fix] # Customize as needed
        types: [sql]
        files: \.(sql)$ # Target SQL files